name: elmed219-2021
dependencies:
- python >= 3.8.0
- pip
- ipython
- ipywidgets
- jupyter
- git
- matplotlib
- pandas
- scikit-learn >= 0.23
- ipykernel
- scipy
- seaborn
- scikit-image
- imageio
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- pip:
  - pip >= 20.0
  - kaggle
  - xlrd
  - eli5
  - pdpbox
  - nibabel
  - nilearn
  - opencv-python
  - numpy==1.19.3 # See https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html
